//
//  UserPoolForgotPasswordViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import Foundation
import UIKit
import AWSCognitoIdentityProvider
import AWSMobileHubHelper

class UserPoolForgotPasswordViewController: UIViewController {
    
    var pool: AWSCognitoIdentityUserPool?
    var user: AWSCognitoIdentityUser?
    
    @IBOutlet weak var userName: UITextField!
    
    var popWait:WaitingViewController?
    @IBAction func onForgotPassword(_ sender: AnyObject) {
        
        popWait = WaitingViewController()
        self.navigationController?.pushViewController(popWait!, animated: true)
        
        guard let username = self.userName.text, !username.isEmpty else {
            DispatchQueue.main.async(execute: {
                self.popWait?.setMessageError(error: "Vous devez saisir un surnom")
            })
            return
        }
        
        self.user = self.pool?.getUser(self.userName.text!)
        self.user?.forgotPassword().continueWith(block: {[weak self] (task: AWSTask) -> AnyObject? in
            guard let strongSelf = self else {return nil}
            DispatchQueue.main.async(execute: {
                if let error = task.error as NSError? {
                    strongSelf.popWait?.setError(error: error)
                } else {
                    
                    let userPoolsStoryboard = UIStoryboard(name: "UserPools", bundle: nil)
                    let newPasswordController = userPoolsStoryboard.instantiateViewController(withIdentifier: "NewPassword") as! UserPoolNewPasswordViewController
                    
                    newPasswordController.user = strongSelf.user
                    
                    strongSelf.navigationController?.pushViewController(newPasswordController, animated: true)
                }
            })
            return nil
        })
    }
    
    @IBAction func onCancel(_ sender: AnyObject) {
        _ = self.navigationController?.popViewController(animated: true)
    }
    
    @IBOutlet weak var btnBack: UIButton!
    @IBOutlet weak var btnForgot: UIButton!
    override func viewDidLoad() {
        super.viewDidLoad()
        self.pool = AWSCognitoIdentityUserPool.init(forKey: AWSCognitoUserPoolsSignInProviderKey)
        
        btnBack.setImage(#imageLiteral(resourceName: "delete").withRenderingMode(.alwaysTemplate), for: .normal)
        btnBack.tintColor = UIColor().primary()
        
        btnForgot.unselectedStyle()
        btnForgot.setImage(#imageLiteral(resourceName: "pirate").withRenderingMode(.alwaysTemplate), for: .normal)
        btnForgot.layer.cornerRadius = btnForgot.frame.size.height/2
    }
}
